FROM golang AS builder
RUN git clone "https://github.com/canonical/pebble.git" /pebble
WORKDIR /pebble
RUN go build -o pebble ./cmd/pebble/
#
WORKDIR /
COPY hello.go /
RUN go build -o hello hello.go

FROM ubuntu
COPY --from=builder /pebble/pebble /
COPY --from=builder /hello /
ENTRYPOINT ["/pebble"]
